# Generated by Django 6.1 on 2026-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('technologies', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tecnologías (separadas por coma)')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='URL de GitHub')),
                ('url_demo', models.URLField(blank=True, null=True, verbose_name='URL de demo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, help_text='Los proyectos se ordenan de menor a mayor', verbose_name='Orden (menor = primero)')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta (ej: GitHub)')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon', models.CharField(help_text='Nombre del icono (ej: github, linkedin, twitter, youtube)', max_length=100, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Enlace social',
                'verbose_name_plural': 'Enlaces sociales',
            },
        ),
    ]
