"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-ihqo%57miw*lt3c+-*j$3pp&zve92mp4&zlv=@w2-#a%-1$3ub'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Hosts permitidos. En desarrollo basta con estos:
#   localhost -> cuando abres http://localhost:8000
#   127.0.0.1 -> la misma dirección pero con la IP
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1'
).split(',')


# Application definition
# Aquí se registran las apps del proyecto. 'core' es nuestra app.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',  # Nuestra app con los modelos del portfolio
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

# Plantillas (HTML que Django puede renderizar).
# DIRS se usa en PRODUCCIÓN para que Django sirva el build de React
# (frontend/dist/index.html) como si fuera una página suya.
# En desarrollo NO se usa: el frontend corre con Vite en el 5173.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'frontend' / 'dist',  # Build de React (SPA)
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# Idioma por defecto: español. Esto traduce el panel admin.
LANGUAGE_CODE = 'es'

# Zona horaria por defecto (los timestamps se guardan en UTC internamente)
TIME_ZONE = 'America/Havana'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# En producción, Django debe servir también los archivos del build de React
# (JS, CSS, imágenes...). Apuntamos a la carpeta 'dist' completa: así
# index.html queda en /static/index.html y los assets en /static/assets/.
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dist',
]

# Carpeta donde se guardan los archivos "recogidos" con collectstatic.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos subidos por el usuario (las imágenes de los proyectos).
# MEDIA_URL es la URL pública (http://localhost:8000/media/...)
# MEDIA_ROOT es la carpeta física donde se guardan.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Tipo de clave primaria automática para los modelos nuevos.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de CORS para permitir que el frontend desplegado acceda
# a la API del backend en Render sin bloqueo por el navegador.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'https://portfolio-ten-rho-trfo331zuu.vercel.app',
    ).split(',')
    if origin.strip()
]

if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ]

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
